git add data.js// src/data.js

export const QUESTIONS = {
    "Number & Algebra": [
        { definition: "Numbers whose absolute values are whole numbers. They consist of positive integers and their corresponding negative counterparts which are called additive inverses.", answer: "INTEGERS" },
        { definition: "Numbers which can be written as a fraction a/b, where a and b are both whole numbers and b is not equal to zero.", answer: "RATIONAL NUMBER" },
        { definition: "Numbers that can’t be expressed as a quotient of two integers a/b, where b is not equal to zero.", answer: "IRRATIONAL NUMBER" },
        { definition: "Made up of the natural numbers and 0. W = {0, 1, 2, 3, 4, 5, …}", answer: "WHOLE NUMBER" },
        { definition: "Numbers used in counting objects. N = {1, 2, 3, 4, 5, …}", answer: "NATURAL NUMBERS" },
        { definition: "System of sets of numbers that make up the set of real numbers.", answer: "REAL NUMBER SYSTEM" },
        { definition: "Used to describe the distance of a number from zero on a number line.", answer: "ABSOLUTE VALUE" },
        { definition: "Line that allows us to visualize real numbers by associating them with unique points on the line.", answer: "NUMBER LINE" },
        { definition: "Unique real number, which when multiplied by itself twice, gives the original number.", answer: "CUBE ROOT" },
        { definition: "Smallest multiple that two or more denominators share.", answer: "LEAST COMMON DENOMINATOR (LCD)" },
        { definition: "Made up of constants, variables, and the operations for the mathematical symbols.", answer: "ALGEBRAIC EXPRESSION" },
        { definition: "Another word for factor, it is an expression multiplied to another expression.", answer: "COEFFICIENT" },
        { definition: "Real number that can be an integer, a fraction, or an irrational number that has a fixed value.", answer: "CONSTANT" },
        { definition: "Placeholder that can be replaced by an unknown value.", answer: "VARIABLE" },
        { definition: "This means “per centum” or per hundred.", answer: "PERCENT" },
        { definition: "The number that represents a part of the base.", answer: "PERCENTAGE" },
        { definition: "Type of percentage change that involves reducing the values at a certain rate.", answer: "PERCENTAGE DECREASE" },
        { definition: "Type of percentage change that involves raising the value at a certain rate.", answer: "PERCENTAGE INCREASE" },
        { definition: "Form of compensation given to employees for selling merchandise.", answer: "COMMISSION" },
        { definition: "The amount charged for the use of borrowed money over a specific period of time.", answer: "INTEREST" },
        { definition: "The amount of money borrowed.", answer: "PRINCIPAL" },
        { definition: "The amount added to the price of an item purchased .", answer: "SALES TAX" },
        { definition: "Interest calculated solely based on the principal.", answer: "SIMPLE INTEREST" },
        { definition: "A comparison of two quantities by division", answer: "RATIO" },
        { definition: "Percent value or the number expressed in percent (%).", answer: "RATE" },
        { definition: "The whole or the total value of something that represents 100%.", answer: "BASE" },
        { definition: "Decimal number that has finite numbers of digits after the decimal point.", answer: "TERMINATING DECIMAL" },
        { definition: "It has a repeating digit or a pattern of repeating digits.", answer: "REPEATING DECIMAL" },
        { definition: "A statement that two mathematical expressions are equal.", answer: "EQUATION" },
        { definition: "an equation involving two or more variables, where each variable represents a specific quantity", answer: "LITERAL EQUATION" },
        { definition: "Mathematical sentence comparing two expressions using inequality symbols (<, >, ≤, ≥, ≠).", answer: "INEQUALITY" },
        { definition: "Value of the variable that makes the equation true.", answer: "SOLUTION" },
        { definition: "The process of assigning a real number to a variable.", answer: "SUBSTITUTION" },
        { definition: "Set is a well-defined collection of objects that have common description or characteristic.", answer: "SET" },
        { definition: "An object that belongs to a set.", answer: "ELEMENT" },
        { definition: "Set that contains all objects under consideration.", answer: "UNIVERSAL SET" },
        { definition: "A set that contains no elements.", answer: "NULL SET" },
        { definition: "The number of elements in the set.", answer: "CARDINALITY" },
        { definition: "Given sets A and B, the set whose elements belong to set A or set B, or both.", answer: "UNION OF SETS" },
        { definition: "Given two sets A and B, the set whose elements are the common elements of set A and B.", answer: "INTERSECTION OF SETS" },
        { definition: "Given two sets A and B, the elements of B that do not belong to A.", answer: "COMPLEMENT OF A SET" },
        { definition: "Sets where intersection of two sets is not an empty set.", answer: "JOINT SETS" },
        { definition: "Sets where the intersection of two sets is a null set.", answer: "DISJOINT SETS" },
        { definition: "Given sets A and B, the set of all elements in set A that are not elements of set B", answer: "SET DIFFERENCE" },
        { definition: "A diagram that uses two or more overlapping shapes such as circles to represent sets.", answer: "VENN DIAGRAM" },
        { definition: "A symbol for an equation", answer: "EQUAL SIGN" },
        { definition: "Line that allows us to visualize real numbers by associating them with unique points on the line", answer: "NUMBER LINE" },
    ],
    "Measurement & Geometry": [
        { definition: "A closed figure on a plane, made up of 3 or more line segments that intersect only at endpoints, with each endpoint belonging to exactly 2 line segments.", answer: "POLYGON" },
        { definition: "The point of intersection of the sides of a polygon.", answer: "VERTEX" },
        { definition: "A polygon that is both equilateral and equiangular.", answer: "REGULAR POLYGON" },
        { definition: "A polygon whose sides are all congruent.", answer: "EQUILATERAL POLYGON" },
        { definition: "A polygon whose angles are congruent.", answer: "EQUIANGULAR POLYGON" },
        { definition: "Lines on the same plane that do not intersect.", answer: "PARALLEL LINES" },
        { definition: "Lines on the same plane that intersect and form a right angle.", answer: "PERPENDICULAR LINES" },
        { definition: "Line that intersects  two or more coplanar lines at different points.", answer: "TRANSVERSAL" },
        { definition: "Angles that are on the same side of the transversal, and are both above or below parallel lines.", answer: "CORRESPONDING ANGLES" },
        { definition: "An angle formed by two adjacent sides of the polygon.", answer: "INTERIOR ANGLE" },
        { definition: "An angle formed outside the polygon by one side of a polygon and the line containing an adjacent side.", answer: "EXTERIOR ANGLE" },
        { definition: "A line segment connecting two non-consecutive vertices of a polygon", answer: "DIAGONAL" },
        { definition: "Angles that have equal measure.", answer: "CONGRUENT ANGLES" },
        { definition: "A polygon that has all interior angles measuring less than 180°.", answer: "CONVEX POLYGON" },
        { definition: "A polygon that has at least one interior angle which measures greater than 180°.", answer: "CONCAVE POLYGON" },
        { definition: "a solid figure that has parallel circular bases, joined by curved surface.", answer: "CYLINDER" },
        { definition: "Two angles whose measures add up to 90°.", answer: "COMPLEMENTARY ANGLES" },
        { definition: "Two angles whose measures add up to 180°.", answer: "SUPPLEMENTARY ANGLES" },
        { definition: "Coplanar angles that share a common side and a common vertex, but no common interior point.", answer: "ADJACENT ANGLES" },
        { definition: "Non-adjacent and congruent angles formed by two intersecting lines.", answer: "VERTICAL ANGLES" },
        { definition: "the angle formed by two adjacent sides of a polygon.", answer: "INTERIOR ANGLES OF A POLYGON" },
        { definition: "an angle formed outside the polygon when one side of the polygon is extended.", answer: "EXTERIOR ANGLES OF A POLYGON" },
        { definition: "Two lines that are adjacent and their non-common sides form a straight line. They are supplementary.", answer: "LINEAR PAIR" },
        { definition: "The process of assigning a number on a measuring device to length, mass, weight, or some other quantity.", answer: "MEASUREMENT" },
        { definition: "The process of finding the equivalent value of a unit of measure in another unit of measure.", answer: "CONVERSION" },
        { definition: "the amount of space occupied by any 3-dimensional figure, measured in cubic units.", answer: "VOLUME" },
        { definition: "A  polyhedron with a polygonal base, and whose lateral faces are triangles meeting at a common vertex known as its apex.", answer: "PYRAMID" },
        { definition: "A pyramid with a square base.", answer: "SQUARE PYRAMID" },
        { definition: "Solid figure usually with more than six faces.", answer: "POLYHEDRON" },
        { definition: "a pyramid with a rectangular base.", answer: "RECTANGULAR PYRAMID" },
        { definition: "A polyhedron with two congruent and parallel bases", answer: "RECTANGULAR PRISM" },
    ],
    "Data & probability": [
        { definition: "Refers to information such as facts and numbers used to analyze something or make decisions.", answer: "DATA" },
        { definition: "The study of collecting, organizing, and analyzing data.", answer: "STATISTICS" },
        { definition: "Data that can be represented by numbers.", answer: "QUANTITATIVE DATA" },
        { definition: "Information that can be grouped into different categories.", answer: "QUALITATIVE DATA" },
        { definition: "a subset of a population that is selected and studied to make inferences or draw conclusions about the population.", answer: "SAMPLE" },
        { definition: "A way of gathering data by watching members of the sample as they move in their natural setting.", answer: "OBSERVATION" },
        { definition: "Watching interactions or patterns of behavior as they occur.", answer: "DIRECT OBSERVATION" },
        { definition: "Looking at the results of interaction or behavior.", answer: "INDIRECT OBSERVATION" },
        { definition: "Sampling technique in which sample is created by choosing members systematically from an ordered list of population", answer: "SYSTEMATIC SAMPLING" },
        { definition: "Tabular arrangement of data that displays the frequency of each possible value or response.", answer: "FREQUENCY DISTRIBUTION TABLE" },
        { definition: "Data presentation technique used to show changes or trends over a straight line.", answer: "LINE GRAPH" },
        { definition: "Effective in showing comparison among data values, by showing varying heights of bars with the same width.", answer: "HISTOGRAM" },
        { definition: "Useful in showing distribution, percentages, or parts of a whole.", answer: "PIE CHART" },
        { definition: "A diagram wherein every data value is divided into its first digit/s (stem) and its last digits (leaf).", answer: "STEM-AND-LEAF PLOT" },
        { definition: "Real number associated with a point", answer: "COORDINATES" },
        { definition: "The result of a single trial of a random experiment", answer: "OUTCOME" },
        { definition: "A subset of the sample space.", answer: "EVENT" },
        { definition: "The set of all possible outcomes of a random experiment", answer: "SAMPLE SPACE" },
        { definition: "An event that will never occur.", answer: "IMPOSSIBLE EVENT" },
        { definition: "An event that is certain to occur.", answer: "SURE EVENT" },
        { definition: "An activity that can be repeated under similar conditions but the outcomes can’t be predicted with certainty.", answer: "RANDOM EXPERIMENT" },
    ],
};